### ISSUE TITLE
No Camera Video Stream when Running on Beaglebone Blue

### ISSUE THREAD

**Issue by ansarid** [remotv/controller#18] opened 2019-10-25 00:04 UTC
**Describe the bug:**
When running `controller.py` on a BeagleBone Blue I am unable to see a video stream on the website but I do get an audio stream.
<br>
**To Reproduce:**
1. Connect a webcam to the BeagleBone Blue USB.
2. Configure `controller.conf` with username, api key, and check that `camera_device = /dev/video0` does exist and matches. (I like to use `ls /dev/video*`). Save and close.
3. Run `python3 controller.py`.
4. I can hear audio through the website fine but video stays black. Below is the output of running `python3 controller.py`.
```
debian@beaglebone:~/remotv$ python controller.py
04:48:27 - controller.py : RemoTV Controller Starting up
modprobe: FATAL: Module bcm2835_wdt not found in directory /lib/modules/4.14.71-ti-r80
aplay: main:788: audio open error: No such file or directory
04:48:29 - controller.py : RemoTV Controller Started
04:48:29 - controller.py : Unknown event type
```
 For comparison, I performed the same steps on a Raspberry Pi and was able to stream both audio and video perfectly fine. Below is the output of `python3 controller.py`.

```
pi@robopi:~/remotv $ python controller.py
14:25:02 - controller.py : RemoTV Controller Starting up
Failed to start watchdog.service: Unit watchdog.service not found.
aplay: main:788: audio open error: No such file or directory
14:25:04 - controller.py : RemoTV Controller Started
14:25:04 - controller.py : Unknown event type
14:25:06 - watchdog.py : Process FFmpegAudioProcess not running, restarting
14:25:06 - watchdog.py : Process FFmpegCameraProcess not running, restarting
```

**Controller Version:**

Running `sh git log -1` outputs:
```
        commit 68bc77f7c9591cd678b5158f0b30c91c462ce42f (HEAD -> master, origin/master,origin/HEAD)
        Author: Bryan Morrison <b.morrison4@students.clark.edu>
        Date:   Wed Oct 23 13:52:46 2019 -0700

            Fix error where ThunderBorg bots would be unable to move

            In my supreme laziness back on LR, I forced all directions to upper case so when we switched to all lowercase commands, no direction would fire.

```

**Comment by SkyeOfBreeze** [comment] 2019-10-26 03:25
@ansarid What does `v4l2-ctl --list-devices` list for you? You want to make sure you are using a camera that shows up there if anything shows up. If that does not work, what webcam is this?

**Comment by ansarid** [comment] 2019-10-28 00:17
@btelman96 

```
debian@beaglebone:~$ v4l2-ctl --list-devices
UVC Camera (046d:0825) (usb-musb-hdrc.1-1):
	/dev/video0
```

I am using the Logitech C270.

**Comment by Nocturnal42** [comment] 2019-10-28 04:10
From Discord: Your problem does not look like an issue with the controller itself. You may want to edit the controller.conf file, and in the logging section set console to DEBUG. That may provide more details, which are probably not going to help. I would suggest taking the ffmpeg command line the controller generates for streaming video, and manually running that from the command line without the controller running. Also, there is a very good chance that ffmpeg is going to struggle  to encode video with a single 1ghz core.

**Comment by ansarid** [comment] 2019-10-28 16:12
Here is the output with DEBUG enabled:
```
debian@beaglebone:~/remotv$ python3 controller.py 
16:09:09 - controller.py : RemoTV Controller Starting up
16:09:09 - controller.py : command line arguments : Namespace(custom_chat=True, custom_hardware=True, custom_tts=True, custom_video=True, ext_chat_command=True, no_camera=False, no_mic=False, robot_key='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InJib3QtNmVlNzZjYWEtNTAzMS00ZTk0LTljZTItOTNiMTZiNjA5NzkyIiwiaWF0IjoxNTcxNzcwNzcxLCJleHAiOjE1NzQzNjI3NzEsInN1YiI6IiJ9.yt3Z8K38xsv585mAWSnKwRJuPCpLiYYtUmb0hzcyXqE', type='none', video='ffmpeg-arecord')
[sudo] password for debian: 
modprobe: FATAL: Module bcm2835_wdt not found in directory /lib/modules/4.14.71-ti-r80
16:09:18 - controller.py : Loading tts
16:09:18 - tts.py : loading module tts/espeak
16:09:18 - tts.py : Unable to find tts/tts_custom.py
16:09:18 - espeak.py : TTS temporary directory : /tmp
16:09:18 - controller.py : Loading networking
16:09:18 - networking.py : configuring web socket wss://remo.tv/
16:09:18 - networking.py : staring websocket listen process
16:09:18 - networking.py : Server Detected
16:09:18 - tts.py : message : ok
aplay: main:788: audio open error: No such file or directory
16:09:18 - networking.py : {"e": "AUTHENTICATE_ROBOT", "d": {"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InJib3QtNmVlNzZjYWEtNTAzMS00ZTk0LTljZTItOTNiMTZiNjA5NzkyIiwiaWF0IjoxNTcxNzcwNzcxLCJleHAiOjE1NzQzNjI3NzEsInN1YiI6IiJ9.yt3Z8K38xsv585mAWSnKwRJuPCpLiYYtUmb0hzcyXqE"}}
16:09:18 - networking.py : websocket connected
16:09:18 - controller.py : {"e":"ROBOT_VALIDATED","d":{"id":"rbot-6ee76caa-5031-4e94-9ce2-93b16b609792","host":"serv-c09da9a6-bf7d-4ad1-95ed-a0ea39c43c1f"}}
16:09:18 - robot_util.py : GET https://remo.tv/api/dev/channels/list/serv-c09da9a6-bf7d-4ad1-95ed-a0ea39c43c1f
16:09:19 - networking.py : getChatChannels : {"channels":[{"host_id":"serv-c09da9a6-bf7d-4ad1-95ed-a0ea39c43c1f","id":"chan-4af89ada-8663-437b-a754-9c86ca66141f","name":"General","chat":"chat-00c2b053-913e-4ecd-8ab1-a66028062e8a","controls":"cont-9e26b7a7-5484-49cf-b648-78c77e95b0ef","display":"","created":"1571679594286","status":{"test_value":true},"settings":{"access":"@everyone","public":true},"robot":null},{"host_id":"serv-c09da9a6-bf7d-4ad1-95ed-a0ea39c43c1f","id":"chan-7cfc8890-640e-4cf8-ac00-0ea6c5d7c692","name":"SCUTTLE","chat":"chat-00c2b053-913e-4ecd-8ab1-a66028062e8a","controls":"cont-7b1202a9-e0de-4a0e-b930-bce19bd22f5e","display":"","created":"1571681305979","status":{"test_value":true},"settings":{"access":"@everyone","public":true},"robot":null}]}
16:09:19 - networking.py : {'channels': [{'settings': {'public': True, 'access': '@everyone'}, 'display': '', 'id': 'chan-4af89ada-8663-437b-a754-9c86ca66141f', 'created': '1571679594286', 'controls': 'cont-9e26b7a7-5484-49cf-b648-78c77e95b0ef', 'robot': None, 'name': 'General', 'host_id': 'serv-c09da9a6-bf7d-4ad1-95ed-a0ea39c43c1f', 'status': {'test_value': True}, 'chat': 'chat-00c2b053-913e-4ecd-8ab1-a66028062e8a'}, {'settings': {'public': True, 'access': '@everyone'}, 'display': '', 'id': 'chan-7cfc8890-640e-4cf8-ac00-0ea6c5d7c692', 'created': '1571681305979', 'controls': 'cont-7b1202a9-e0de-4a0e-b930-bce19bd22f5e', 'robot': None, 'name': 'SCUTTLE', 'host_id': 'serv-c09da9a6-bf7d-4ad1-95ed-a0ea39c43c1f', 'status': {'test_value': True}, 'chat': 'chat-00c2b053-913e-4ecd-8ab1-a66028062e8a'}]}
16:09:19 - networking.py : channel  NOT found, joining : chan-4af89ada-8663-437b-a754-9c86ca66141f
16:09:19 - networking.py : internet connected
16:09:19 - controller.py : Loading hardware module
16:09:19 - controller.py : Loading module hardware/none
16:09:19 - controller.py : Unable to find hardware/hardware_custom.py
16:09:19 - controller.py : Loading video module
16:09:19 - controller.py : Loading module video/ffmpeg-arecord
16:09:19 - controller.py : {"e":"SEND_CHAT","d":{"name":"General","id":"chat-00c2b053-913e-4ecd-8ab1-a66028062e8a","host_id":"serv-c09da9a6-bf7d-4ad1-95ed-a0ea39c43c1f","messages":[],"created":"1571679594285"}}
16:09:19 - controller.py : Unknown event type
16:09:19 - controller.py : Unable to find video/video_custom.py
16:09:19 - ffmpeg.py : Video start count : 1
16:09:19 - ffmpeg.py : videoCommandLine : /usr/bin/ffmpeg -f v4l2 -framerate 25 -video_size 768x432 -r 25  -i /dev/video0  -f mpegts -codec:v mpeg1video -b:v 350k -bf 0 -muxdelay 0.001 -nostats -threads 2 http://remo.tv:1567/transmit?name=chan-4af89ada-8663-437b-a754-9c86ca66141f-video
16:09:19 - controller.py : Loading extended chat commands
16:09:19 - extended_command.py : Moderators : 
16:09:19 - ffmpeg-arecord.py : audioCommandLine : /usr/bin/arecord -D hw:1,0 -c 1 -f S16_LE -r 44100 | /usr/bin/ffmpeg -i - -ar 44100 -f mpegts -codec:a mp2  -b:a 32k -bufsize 8192k -muxdelay 0.001 -nostats http://remo.tv:1567/transmit?name=chan-4af89ada-8663-437b-a754-9c86ca66141f-audio
16:09:19 - controller.py : Unable to find chat_custom.py
16:09:19 - controller.py : RemoTV Controller Started
16:09:31 - controller.py : {"e":"ROBOT_SERVER_UPDATED"}
16:09:46 - controller.py : {"e":"ROBOT_SERVER_UPDATED"}
16:10:01 - controller.py : {"e":"ROBOT_SERVER_UPDATED"}
```

And here is the output when just running the ffmpeg command:
```
debian@beaglebone:~/remotv$ /usr/bin/ffmpeg -f v4l2 -framerate 25 -video_size 768x432 -r 25  -i /dev/video0  -f mpegts -codec:v mpeg1video -b:v 350k -bf 0 -muxdelay 0.001 -nostats -threads 2 http://remo.tv:1567/transmit?name=chan-4af89ada-8663-437b-a754-9c86ca66141f-video
ffmpeg version 3.2.14-1~deb9u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[video4linux2,v4l2 @ 0xb14c80] The V4L2 driver changed the video from 768x432 to 752x416
```

**Comment by Nocturnal42** [comment] 2019-10-31 14:03
There are no errors there, and if ffmpeg is actually running without error, you should be gettings video. you can try removing the `-nostats` from the ffmpeg line, to see information about framerate / bitrate and video quality.

**Comment by ansarid** [comment] 2019-10-31 19:04
@Nocturnal42 I ran ffmpeg with the -nostats option removed and got this output:
```
debian@beaglebone:~/remotv$ /usr/bin/ffmpeg -f v4l2 -framerate 25 -video_size 768x432 -r 25  -i /dev/video0  -f mpegts -codec:v mpeg1video -b:v 350k -bf 0 -muxdelay 0.001 -threads 2 http://remo.tv:1567/transmit?name=chan-4af89ada-8663-437b-a754-9c86ca66141f-video
ffmpeg version 3.2.14-1~deb9u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[video4linux2,v4l2 @ 0x1caec80] The V4L2 driver changed the video from 768x432 to 752x416
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, bitrate: 125132 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 752x416, 125132 kb/s, 25 fps, 25 tbr, 1000k tbn, 1000k tbc
http://remo.tv:1567/transmit?name=chan-4af89ada-8663-437b-a754-9c86ca66141f-video: Immediate exit requested
Exiting normally, received signal 2.
```

When I ran the command, the outputs stopped at the line `[video4linux2,v4l2 @ 0x1caec80] The V4L2 driver changed the video from 768x432 to 752x416` until I hit `Ctrl+C` after which the rest of the output shows up. Is that normal?

**Comment by Nocturnal42** [comment] 2019-11-01 18:29
What you should see, should look more like this.
```
Input #0, image2, from 'video/Remo.png':
  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgba(pc), 512x461, 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> mpeg1video (native))
Press [q] to stop, [?] for help
Output #0, mpegts, to 'http://remo.tv:1567/transmit?name=chan-d196f21a-1fb6-4ff1-8dbd-beb24deebdca-video':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: mpeg1video, yuv420p, 512x461, q=2-31, 350 kb/s, 25 fps, 90k tbn, 25 tbc
    Metadata:
      encoder         : Lavc57.89.100 mpeg1video
    Side data:
      cpb: bitrate max/min/avg: 0/0/350000 buffer size: 0 vbv_delay: -1

```
Followed by a lot of lines like this, that report the details of the stream.
`frame=  205 fps= 61 q=1.6 Lsize=     418kB time=00:00:08.12 bitrate= 421.6kbits/s speed=2.43x`

The message about changing resolutions is normal, in that you have asked for a resolution the camera does not support, so the drive has changed the resolution to one actually supported by the camera. It should not impact your ability to stream video, but you can list supported camera resolutions with `v4l2-ctl --list-formats`.

It looks like you are experiencing one of two possibilities. First would be an inability to connect to the video relay. Since you can transmit audio, this is highly unlikely. If it were the case, ffmpeg would fail with an error message after a minute or so.

The other possibility is that ffmpeg is not actually getting any video frames from the camera.

**Comment by bwookieeeee** [comment] 2019-11-02 20:19
I'm inclined to close this issue as invalid since it's becoming apparent that this is not the fault of the controller software.

**Comment by Nocturnal42** [comment] 2019-11-03 12:56
I'm inclined to leave it. It's not a bug in the controller, but it is a valid request for support.

**Comment by ansarid** [comment] 2019-11-04 17:13
@Nocturnal42 This is this output I get when I run the command `v4l2-ctl --list-formats`:
```
debian@beaglebone:~$ v4l2-ctl --list-formats
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG
```
I'm unsure how to test if ffmpeg is getting frames from the camera. What would be the best way for me to test this? I know the camera works because I am able to connect it to my laptop as well as grab frames from the camera from OpenCV on the BeagleBone. This would mean that this is a ffmpeg problem? Please let me know what other things I could try or what other information I could give you to help me resolve this issue.

**Comment by Nocturnal42** [comment] 2019-11-15 12:31
You could try `/usr/bin/ffmpeg -f v4l2 -framerate 25 -video_size 768x432 -r 25  -i /dev/video0 -vframes 1 output.jpg` which should grab 1 frame from the camera and write it to output.jpg.

You could also run `v4l2-ctl --list-framesizes=YUYV` which should list what resolutions your camera supports. If the command above does not output an image, try changing the resolution to one from this list.

**Comment by ansarid** [comment] 2019-11-18 17:39
@Nocturnal42 I've managed to get the video to stream by bringing down the video resolution and framerate. The framerate is a bit too slow still so I'm wondering if anyone can help me refine this command since I'm not quite experienced with `ffmpeg`.

`/usr/bin/ffmpeg -f v4l2 -framerate 5 -video_size 640x480 -r 5 -i /dev/video0 -f mpegts -codec:v mpeg1video -b:v 350k -bf 0 -muxdelay 0.001 -threads 2 -filter:v "setpts=0.2*PTS,fps=25" http://remo.tv:1567/transmit?name=chan-#################################-video`

After I brought the frame rate down, `ffmpeg` would not allow me to stream with `mpeg1video` stating the framerate had to be at least 25fps which is why I had to add the `-filter:v "setpts=0.2*PTS,fps=25"` argument. 

**EDIT:**
I got great results using:

`/usr/bin/ffmpeg -f v4l2 -framerate 12.5 -video_size 384x216 -r 12.5 -i /dev/video0 -f mpegts -crf 51 -codec:v mpeg1video -b:v 700k -bf 0 -muxdelay 0.001 -threads 2 -filter:v "setpts=0.5*PTS,fps=25" http://remo.tv:1567/transmit?name=chan-#################################-video`

We matched the framerate and video speed which is obviously important. I had done a poor job of that before.

I'd recommend some changes to `ffmpeg.py` and add some more `ffmpeg` properties to the `controller.conf` such as frame rate. We were unable to capture at 25 frames per second which is why we had to bring down out frame rate and then slow down the video using the ` -filter:v "setpts=0.5*PTS,fps=25"` argument.

Unless there are any other recommendations I would be fine with closing this issue.

**Comment by Nocturnal42** [comment] 2019-11-21 05:55
Glad it's working. I did mention way back, that the beaglebone was going to struggle encoding video. What most people do when using limited hardware, is stream an MJPG video stream (which most cameras support natively) to a second, usually desktop, machine that re-encodes the video and streams it to the site. It increases video latency, but you should be able to get a much better resolution and frame rate. 

I haven't done MJPG restreaming in a while, so you'd be better asking in the discord as I know at least one or two people currently are doing it and will be able to better point out what changes are required to make it work.

I never added the framerate as an option, because it needs to be 25 for mpeg encoding, but since you have come up with an interesting way around that, I will add it shortly.

**Closed as completed** 2020-01-15 20:46 UTC
Labels: help wanted
